// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type AvailableDates struct {
	Dates []DateInfo `json:"dates"`
}

type AvailableDatesRes struct {
	Code    int            `json:"code"`
	Message string         `json:"message"`
	Data    AvailableDates `json:"data"`
}

type DateInfo struct {
	Type string `json:"type"`
	Date string `json:"date"`
}

type EmptyData struct {
}

type FeedbackReq struct {
	Content string `json:"content"`
}

type GeneralRes struct {
	Code    int       `json:"code"`
	Message string    `json:"message"`
	Data    EmptyData `json:"data"`
}

type LoginData struct {
	Name      string `json:"name"`
	StudentId string `json:"student_id"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginRes struct {
	Code    int       `json:"code"`
	Message string    `json:"message"`
	Data    LoginData `json:"data"`
}

type MyReservationRes struct {
	Code    int                `json:"code"`
	Message string             `json:"message"`
	Data    ReservationDetails `json:"data"`
}

type ReservationData struct {
	RoomID        int    `json:"room_id"`
	Seat          string `json:"seat"`
	Date          string `json:"date"`
	Type          string `json:"type"`
	ReservationID int    `json:"reservation_id"`
}

type ReservationDetails struct {
	ID     int    `json:"id"`
	Type   string `json:"type"`
	Date   string `json:"date"`
	Room   string `json:"room"`
	SeatID int    `json:"seat_id"`
	Status string `json:"status"`
}

type ReserveSeatReq struct {
	Type   string `json:"type"`
	Date   string `json:"date"`
	Room   string `json:"room"`
	SeatID int    `json:"seat_id"`
}

type ReserveSeatRes struct {
	Code    int             `json:"code"`
	Message string          `json:"message"`
	Data    ReservationData `json:"data"`
}

type RoomList struct {
	Rooms []string `json:"rooms"`
}

type RoomListRes struct {
	Code    int      `json:"code"`
	Message string   `json:"message"`
	Data    RoomList `json:"data"`
}

type SeatInfo struct {
	SeatID int    `json:"seat_id"`
	Status string `json:"status"`
}

type SeatListData struct {
	Room  string     `json:"room"`
	Date  string     `json:"date"`
	Seats []SeatInfo `json:"seats"`
}

type SeatListRes struct {
	Code    int          `json:"code"`
	Message string       `json:"message"`
	Data    SeatListData `json:"data"`
}
