// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type AvailableDates struct {
	Dates []DateInfo `json:"dates"`
}

type AvailableDatesRes struct {
	Base
	Data AvailableDates `json:"data"`
}

type Base struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type CancelReservationReq struct {
	ID string `path:"id"`
}

type DateInfo struct {
	Type string `json:"type"`
	Date string `json:"date"`
}

type EmptyData struct {
}

type Feedback struct {
	Content   string `json:"content"`
	StudentId string `json:"student_id"`
}

type FeedbackReq struct {
	Content string `json:"content"`
}

type FeedbackRes struct {
	Base Base
	Data []Feedback `json:"feedback"`
}

type GeneralRes struct {
	Base
	Data EmptyData `json:"data"`
}

type LoginData struct {
	Name      string `json:"name"`
	StudentId string `json:"student_id"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginRes struct {
	Base
	Data LoginData `json:"data"`
}

type MyReservationRes struct {
	Base
	Data []ReservationDetails `json:"data"`
}

type MyScoreRes struct {
	Base
	Data ScoreData `json:"data"`
}

type ReservationData struct {
	RoomID        string `json:"room_id"`
	Seat          string `json:"seat"`
	Date          string `json:"date"`
	Type          string `json:"type"`
	ReservationID int    `json:"reservation_id"`
}

type ReservationDetails struct {
	ID     int    `json:"id"`
	Type   string `json:"type"`
	Date   string `json:"date"`
	Room   string `json:"room"`
	SeatID string `json:"seat_id"`
	Status string `json:"status"`
}

type ReserveSeatReq struct {
	Type   string `json:"type"`
	Date   string `json:"date"`
	Room   string `json:"room"`
	SeatID string `json:"seat_id"`
}

type ReserveSeatRes struct {
	Base
	Data ReservationData `json:"data"`
}

type RoomList struct {
	Rooms []string `json:"rooms"`
}

type RoomListRes struct {
	Base
	Data RoomList `json:"data"`
}

type ScoreData struct {
	Score int `json:"score"`
}

type SeatInfo struct {
	SeatID int    `json:"seat_id"`
	Status string `json:"status"`
}

type SeatListData struct {
	Room  string     `json:"room"`
	Date  string     `json:"date"`
	Seats []SeatInfo `json:"seats"`
}

type SeatListRes struct {
	Base
	Data SeatListData `json:"data"`
}

type CheckIn struct {
	Seatid string `form:"seat_id"`
}
