// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	reservationFieldNames          = builder.RawFieldNames(&Reservation{})
	reservationRows                = strings.Join(reservationFieldNames, ",")
	reservationRowsExpectAutoSet   = strings.Join(stringx.Remove(reservationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	reservationRowsWithPlaceHolder = strings.Join(stringx.Remove(reservationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheReservationIdPrefix = "cache:reservation:id:"
)

type (
	reservationModel interface {
		Insert(ctx context.Context, data *Reservation) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Reservation, error)
		Update(ctx context.Context, data *Reservation) error
		Delete(ctx context.Context, id int64) error
	}

	defaultReservationModel struct {
		sqlc.CachedConn
		table string
	}

	Reservation struct {
		Id        int64     `db:"id"`         // 预约 ID
		StudentId string    `db:"student_id"` // 学号
		Type      string    `db:"type"`       // 预约类型
		Date      time.Time `db:"date"`       // 预约日期
		Room      string    `db:"room"`       // 房间
		SeatId    int64     `db:"seat_id"`    // 座位 ID
		Status    string    `db:"status"`     // 预约状态
	}
)

func newReservationModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultReservationModel {
	return &defaultReservationModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`reservation`",
	}
}

func (m *defaultReservationModel) Delete(ctx context.Context, id int64) error {
	reservationIdKey := fmt.Sprintf("%s%v", cacheReservationIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, reservationIdKey)
	return err
}

func (m *defaultReservationModel) FindOne(ctx context.Context, id int64) (*Reservation, error) {
	reservationIdKey := fmt.Sprintf("%s%v", cacheReservationIdPrefix, id)
	var resp Reservation
	err := m.QueryRowCtx(ctx, &resp, reservationIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", reservationRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultReservationModel) Insert(ctx context.Context, data *Reservation) (sql.Result, error) {
	reservationIdKey := fmt.Sprintf("%s%v", cacheReservationIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, reservationRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.StudentId, data.Type, data.Date, data.Room, data.SeatId, data.Status)
	}, reservationIdKey)
	return ret, err
}

func (m *defaultReservationModel) Update(ctx context.Context, data *Reservation) error {
	reservationIdKey := fmt.Sprintf("%s%v", cacheReservationIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, reservationRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.StudentId, data.Type, data.Date, data.Room, data.SeatId, data.Status, data.Id)
	}, reservationIdKey)
	return err
}

func (m *defaultReservationModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheReservationIdPrefix, primary)
}

func (m *defaultReservationModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", reservationRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultReservationModel) tableName() string {
	return m.table
}
