// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	roomFieldNames          = builder.RawFieldNames(&Room{})
	roomRows                = strings.Join(roomFieldNames, ",")
	roomRowsExpectAutoSet   = strings.Join(stringx.Remove(roomFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	roomRowsWithPlaceHolder = strings.Join(stringx.Remove(roomFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRoomIdPrefix = "cache:room:id:"
)

type (
	roomModel interface {
		Insert(ctx context.Context, data *Room) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Room, error)
		Update(ctx context.Context, data *Room) error
		Delete(ctx context.Context, id int64) error
	}

	defaultRoomModel struct {
		sqlc.CachedConn
		table string
	}

	Room struct {
		Id     int64  `db:"id"`     // 房间 ID
		Room   string `db:"room"`   // 房间
		Status string `db:"status"` // 预约状态
	}
)

func newRoomModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultRoomModel {
	return &defaultRoomModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`room`",
	}
}

func (m *defaultRoomModel) Delete(ctx context.Context, id int64) error {
	roomIdKey := fmt.Sprintf("%s%v", cacheRoomIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, roomIdKey)
	return err
}

func (m *defaultRoomModel) FindOne(ctx context.Context, id int64) (*Room, error) {
	roomIdKey := fmt.Sprintf("%s%v", cacheRoomIdPrefix, id)
	var resp Room
	err := m.QueryRowCtx(ctx, &resp, roomIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", roomRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRoomModel) Insert(ctx context.Context, data *Room) (sql.Result, error) {
	roomIdKey := fmt.Sprintf("%s%v", cacheRoomIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, roomRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Room, data.Status)
	}, roomIdKey)
	return ret, err
}

func (m *defaultRoomModel) Update(ctx context.Context, data *Room) error {
	roomIdKey := fmt.Sprintf("%s%v", cacheRoomIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, roomRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Room, data.Status, data.Id)
	}, roomIdKey)
	return err
}

func (m *defaultRoomModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRoomIdPrefix, primary)
}

func (m *defaultRoomModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", roomRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultRoomModel) tableName() string {
	return m.table
}
