// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	seatFieldNames          = builder.RawFieldNames(&Seat{})
	seatRows                = strings.Join(seatFieldNames, ",")
	seatRowsExpectAutoSet   = strings.Join(stringx.Remove(seatFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	seatRowsWithPlaceHolder = strings.Join(stringx.Remove(seatFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheSeatIdPrefix           = "cache:seat:id:"
	cacheSeatSeatRoomDatePrefix = "cache:seat:seat:room:date:"
)

type (
	seatModel interface {
		Insert(ctx context.Context, data *Seat) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Seat, error)
		FindOneBySeatRoomDate(ctx context.Context, seat string, room string, date time.Time) (*Seat, error)
		Update(ctx context.Context, data *Seat) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSeatModel struct {
		sqlc.CachedConn
		table string
	}

	Seat struct {
		Id     int64     `db:"id"`     // 主键 ID，自增
		Seat   string    `db:"seat"`   // 座位编号
		Room   string    `db:"room"`   // 房间名称
		Date   time.Time `db:"date"`   // 预约日期
		Status string    `db:"status"` // 状态，如 available/booked
	}
)

func newSeatModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSeatModel {
	return &defaultSeatModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`seat`",
	}
}

func (m *defaultSeatModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	seatIdKey := fmt.Sprintf("%s%v", cacheSeatIdPrefix, id)
	seatSeatRoomDateKey := fmt.Sprintf("%s%v:%v:%v", cacheSeatSeatRoomDatePrefix, data.Seat, data.Room, data.Date)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, seatIdKey, seatSeatRoomDateKey)
	return err
}

func (m *defaultSeatModel) FindOne(ctx context.Context, id int64) (*Seat, error) {
	seatIdKey := fmt.Sprintf("%s%v", cacheSeatIdPrefix, id)
	var resp Seat
	err := m.QueryRowCtx(ctx, &resp, seatIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", seatRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSeatModel) FindOneBySeatRoomDate(ctx context.Context, seat string, room string, date time.Time) (*Seat, error) {
	seatSeatRoomDateKey := fmt.Sprintf("%s%v:%v:%v", cacheSeatSeatRoomDatePrefix, seat, room, date)
	var resp Seat
	err := m.QueryRowIndexCtx(ctx, &resp, seatSeatRoomDateKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `seat` = ? and `room` = ? and `date` = ? limit 1", seatRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, seat, room, date); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSeatModel) Insert(ctx context.Context, data *Seat) (sql.Result, error) {
	seatIdKey := fmt.Sprintf("%s%v", cacheSeatIdPrefix, data.Id)
	seatSeatRoomDateKey := fmt.Sprintf("%s%v:%v:%v", cacheSeatSeatRoomDatePrefix, data.Seat, data.Room, data.Date)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, seatRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Seat, data.Room, data.Date, data.Status)
	}, seatIdKey, seatSeatRoomDateKey)
	return ret, err
}

func (m *defaultSeatModel) Update(ctx context.Context, newData *Seat) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	seatIdKey := fmt.Sprintf("%s%v", cacheSeatIdPrefix, data.Id)
	seatSeatRoomDateKey := fmt.Sprintf("%s%v:%v:%v", cacheSeatSeatRoomDatePrefix, data.Seat, data.Room, data.Date)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, seatRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Seat, newData.Room, newData.Date, newData.Status, newData.Id)
	}, seatIdKey, seatSeatRoomDateKey)
	return err
}

func (m *defaultSeatModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheSeatIdPrefix, primary)
}

func (m *defaultSeatModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", seatRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSeatModel) tableName() string {
	return m.table
}
